server:
  port: 9092
  servlet:
    session:
      timeout: 1m
spring:
  freemarker:
    cache: false # 缓存配置 开发阶段应该配置为false 因为经常会改
    suffix: .html # 模版后缀名 默认为ftl
    charset: UTF-8 # 文件编码
    template-loader-path: classpath:/templates/
    settings:
      template_update_delay: 0
  application:
    name: spring security form login
  security:
    user:
      name: admin
      password: 123456
    loginType: html
